name: ntcservicecode
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.0
  flutter_phone_direct_caller: ^2.0.0
  flutter_sms: ^2.3.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

